### PR TITLE
Add rule to forward to swagger api docs

### PR DESCRIPTION
**Pull request by acron0**

### CODE REVIEW

**Comment by elisehuard** [comment]
:shipit:

**Comment by sw1nn** [comment]
Did you consider having an explicit rule for the website bits (ie. images, css html) and then just passing everything else through to witan.app?

**Comment by acron0** [comment]
@sw1nn I didn't. Would that be a "better" way?

**Comment by sw1nn** [comment]
not sure, it would mean that you wouldn't have to add new rules for every new route in the webapp.

**Comment by acron0** [comment]
@sw1nn Gonna stick with this for now but if we find ourselves adding any more rules then I definitely agree this needs looking at

**Pull request merged**
